services:
  internal-api:
    build: .
    container_name: stellaric-internal-api
    restart: unless-stopped
    ports:
      - "3050:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
